name: py369
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.6.9
  - ipykernel==5.1.4
  - notebook==6.0.3
  - jupyter-offlinenotebook==0.1.0
  - jupyterlab==2.0.0
  - jupytext==1.4.0
